Fix the following bug:
make runable
fab local runable
Traceback (most recent call last):
  File "/Users/olive/.virtualenvs/1flow/src/fabric/fabric/main.py", line 739, in main
    *args, **kwargs
  File "/Users/olive/.virtualenvs/1flow/src/fabric/fabric/tasks.py", line 354, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/olive/.virtualenvs/1flow/src/fabric/fabric/tasks.py", line 123, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/olive/.virtualenvs/1flow/src/sparks/sparks/django/fabfile.py", line 1417, in runable
    sparks_roles=('__any__', ))
  File "/Users/olive/.virtualenvs/1flow/src/sparks/sparks/fabric/__init__.py", line 148, in execute_or_not
    if env.host_string.role is None:
AttributeError: 'str' object has no attribute 'role'
make: *** [runable] Error 1